info:
  component: Load-Balance-Service

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    load-balance-service:
      path: /load-balance-service/**
#      stripPrefix: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO