info:
  component: Authentication-Service

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    productcomposite:
      path: /authentication-service/**
#      stripPrefix: false

server:
  port: 8755

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO